name: Build Client

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install MinGW-w64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install dependencies
        run: go mod download

      - name: Build
        shell: bash
        run: |
          VERSION=$(git describe --tags --always 2>/dev/null || echo "unknown")
          BUILD_TIME=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')
          export GOOS=windows
          export GOARCH=${{ matrix.goarch }}
          export CGO_ENABLED=1
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          LDFLAGS="-X \"github.com/newton-miku/now-playing-service-go/tools.Version=${VERSION}\" -X \"github.com/newton-miku/now-playing-service-go/tools.BuildTime=${BUILD_TIME}\" -w -s -H=windowsgui"
          go build -trimpath -ldflags "${LDFLAGS}" -o bin/now-playing-windows-${{ matrix.goarch }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: now-playing-windows-${{ matrix.goarch }}
          path: bin/now-playing-windows-${{ matrix.goarch }}.exe
